### ISSUE TITLE
Parse error for field "tcpinfo_direction"

### ISSUE THREAD

**Issue by Wadikkk** [codeout/fluent-plugin-sflow#2]
I'm using Host Sflow as sflow generator (http://www.sflow.net/)
System: CentOS Linux release 7.3.1611 (Core)
Parsing error appear, when i'm enabling "tcp { }" option in hsflowd configuration (for additional tcp fields)

**Error from td-agent.log**:
Unexpected error on parsing raw="\x00\x00\x00\x05\x00\x00\x00\x01\xC0\xA8\x14\x86\x00\x01\x86\xA0\x00\x00\x1C\xB8\x01\xB2\xDD\x1C\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\xB4\x00\x00)\x91\x00\x00\x00\x02\x00\x00\x00\n\x00\x01\x9F\xAA\x00\x00\x00\x00?\xFF\xFF\xFF\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\b\xA1\x00\x00\x000\x00\x00\x00\x02\x00\x00\x05\xA8\x00\x00\x02\x18\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\xDC\x00\x00\x19\xF5\x00\x00\rJ\x00\x00\x00\n\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00T\x00\x00\x00\x01\x00\x00\x00T\x00\x00\x00\x04\x00\x00\x00Bp\x85\xC2:c\x19\x00\f)\f\xE8\x04\b\x00E\x00\x004\xECh@\x00@\x06qp\xC0\xA8\x14\x86N\x9A\xB9\"\xC9F\x00P\x1E$)\xAE\xCA\x11\xDB\xAD\x80\x10\x05\x1D\xDD\x11\x00\x00\x01\x01\b\n0\xA1_\xF6\n\xF7\x80\xB7\x00\x00" exporter="127.0.0.1" error_class=JSON::ParserError error="399: unexpected token at '{\"sample_type_tag\":\"0:1\",\"sample_type\":\"flow_sample\",\"sample_sequence_no\":10641,\"source_id\":\"0:2\",\"mean_skip_count\":10,\"sample_pool\":106410,\"drop_events\":0,\"input_port\":1073741823,\"output_port\":2,\"flow_block_tag\":\"0:2209\",tcpinfo_direction\":\"sent\",\"tcpinfo_send_mss\":1448,\"tcpinfo_receive_mss\":536,\"tcpinfo_unacked_pkts\":0,\"tcpinfo_lost_pkts\":0,\"tcpinfo_retrans_pkts\":0,\"tcpinfo_path_mtu\":1500,\"tcpinfo_rtt_us\":6645,\"tcpinfo_rtt_us_var\":3402,\"tcpinfo_send_congestion_win\":10,\"tcpinfo_reordering\":3,\"tcpinfo_rtt_us_min\":0,\"flow_block_tag\":\"0:1\",\"header_protocol\":1,\"sampled_packet_size\":84,\"stripped_bytes\":4,\"header_len\":66,\"header_bytes\":\"70-85-C2-3A-63-19-00-0C-29-0C-E8-04-08-00-45-00-00-34-EC-68-40-00-40-06-71-70-C0-A8-14-86-4E-9A-B9-22-C9-46-00-50-1E-24-29-AE-CA-11-DB-AD-80-10-05-1D-DD-11-00-00-01-01-08-0A-30-A1-5F-F6-0A-F7-80-B7\",\"dst_mac\":\"7085c23a6319\",\"src_mac\":\"000c290ce804\",\"ip_size\":66,\"ip_tot_len\":52,\"src_ip\":\"192.168.20.134\",\"dst_ip\":\"78.154.185.34\",\"ip_protocol\":6,\"ip_tos\":0,\"ip_ttl\":64,\"ip_id\":26860,\"tcp_src_port\":51526,\"tcp_dst_port\":80,\"tcp_flags\":16}]}'"

As u can see, there is no quote before tcpinfo_direction field.

[sflow_parse_error.pcap.zip](https://github.com/codeout/fluent-plugin-sflow/files/1288429/sflow_parse_error.pcap.zip)

**Comment by codeout** [comment]
Thanks for your report. We have to add missing ```"``` as you said, let me take a look during this weekend.

**Comment by codeout** [comment]
Fixed versions have been just released. Attached .pcap was very helpful, Thanks !

* v0.3.1 for Fluentd v0.14
* v0.2.1 for Fluentd v0.12

**Comment by Wadikkk** [comment]
@codeout Thanks for your quick response!
